# Generated by Django 5.2.1 on 2025-05-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='on_sale',
            field=models.BooleanField(default=False, verbose_name='Is this a sale price?'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='pre_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Original Price (before sale)'),
        ),
    ]
