# Generated by Django 5.2.1 on 2025-05-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_pricehistory_on_sale_pricehistory_pre_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='product_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Product URL (Optional)'),
        ),
    ]
