# Generated by Django 5.2.1 on 2025-05-30 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_pricehistory_product_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the attribute group (e.g., Nutritional Information, Physical Dimensions)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description for the group.', null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which to display groups.')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AttributeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the attribute (e.g., Fat, Width, Processor Speed)', max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='A unique slug for programmatic access. Auto-generated if blank.', max_length=120, unique=True)),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement (e.g., g, cm, GHz). Leave blank if not applicable.', max_length=30, null=True)),
                ('value_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean (Yes/No)')], default='text', help_text='The type of value this attribute holds.', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional description or help text for this attribute.', null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which to display attributes within a group.')),
                ('group', models.ForeignKey(help_text='The group this attribute belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.attributegroup')),
            ],
            options={
                'ordering': ['group', 'display_order', 'name'],
                'unique_together': {('group', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ItemSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, help_text='Text representation of the value.', null=True)),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=5, help_text='Numeric value, if applicable.', max_digits=15, null=True)),
                ('value_boolean', models.BooleanField(blank=True, help_text='Boolean value, if applicable. Null means not set.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_values', to='catalog.attributedefinition')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='catalog.item')),
            ],
            options={
                'verbose_name': 'Item Specification',
                'verbose_name_plural': 'Item Specifications',
                'ordering': ['attribute__group__display_order', 'attribute__display_order', 'attribute__name'],
                'unique_together': {('item', 'attribute')},
            },
        ),
    ]
